### ISSUE TITLE
2.3.1 installation broken

### ISSUE THREAD

**Issue by cnoergaard** [rubenv/angular-gettext#292]
I can not install the latest version via npm

npm ERR! angular-gettext@2.3.1 install: `./node_modules/protractor/bin/webdriver-manager update`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the angular-gettext@2.3.1 install script './node_modules/protractor/bin/webdriver-manager update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-gettext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-gettext
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-gettext
npm ERR! There is likely additional logging output above.

**Comment by rubenv** [comment]
Right, that's a dev dependency. Fixing

**Comment by rubenv** [comment]
Fixed in `v2.3.3`.

**Comment by dmartinho** [comment]
Hi rubenv ! Great work, but it's not really fixed ^^' : 

npm ERR! angular-gettext@2.3.3 install: `if [ -x ./node_modules/protractor/bin/webdriver-manager ]; then ./node_modules/protractor/bin/webdriver-manager update; fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-gettext@2.3.3 install script 'if [ -x ./node_modules/protractor/bin/webdriver-manager ]; then ./node_modules/protractor/bin/webdriver-manager update; fi'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-gettext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     if [ -x ./node_modules/protractor/bin/webdriver-manager ]; then ./node_modules/protractor/bin/webdriver-manager update; fi
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-gettext
npm ERR! There is likely additional logging output above.

**Comment by cnoergaard** [comment]
Weird - it is working fine for me now

**Comment by crissdev** [comment]
FYI, this happens on Windows.


`node: v6.2.1`
`npm : 3.9.3`

**Comment by rubenv** [comment]
Pushed `v2.3.4`, which should work on Windows as well.

**Comment by dmartinho** [comment]
It works ! Thanks.
